name: 'Get and Cache dependicies'
description: 'Get the dependicies and cache them'
runs:
  using: composite
  steps:
    - name: Use the cached Dependencies
      uses: actions/upload-artifact@v4
      with:
        path: node_modules
        key: node-deps-${{hashfile(**/package-lock.json)}}
    - name: Install the dependicies
      run: npm ci
      shell: bash