name: 'Get and Cache Dependencies'
description: 'Install and cache node_modules using actions/cache'

runs:
  using: 'composite'
  steps:
    - name: Use cached dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node-deps-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-deps-

    - name: Install dependencies
      run: npm ci
      shell: bash
